import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'
import { UserProvider } from './context/userProvider'
import { SocketProvider } from './context/socketProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'WeCommunicate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Navbar />
          <div className='mt-10'>
            <SocketProvider>
              {children}
            </SocketProvider>
          </div>
          <div className='h-1/5 mb-20'></div>
        </UserProvider>
        <Footer />
      </body>
    </html>
  )
}
